# Generated by Django 4.2 on 2023-07-08 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=55)),
                ("location", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=13)),
                (
                    "industry_type",
                    models.CharField(
                        choices=[
                            ("Agriculture", "Agriculture"),
                            ("Engineering", "Engineering"),
                            ("Health Care", "Health Care"),
                            ("Hospitality and Tourism", "Hospitality and Tourism"),
                            ("Aerospace", "Aerospace"),
                            ("Transport and Logistics", "Transport and Logistics"),
                            ("Banking and Finance", "Banking and Finance"),
                            ("Media and Entertainment", "Media and Entertainment"),
                            ("Professional Services", "Professional Services"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=25,
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "title",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
                (
                    "fulltime_partime",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                        ],
                        default="Full Time",
                        max_length=10,
                    ),
                ),
                (
                    "offline_remote",
                    models.CharField(
                        choices=[("Offline", "Offline"), ("Remote", "Remote")],
                        default="Offline",
                        max_length=7,
                    ),
                ),
                ("submission_deadline", models.DateField(max_length=30)),
                ("selection_step", models.PositiveIntegerField()),
                ("salary_range", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                ("skills", models.CharField(max_length=100, null=True)),
                (
                    "date_created",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HirePilot.employer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("resume", models.FileField(upload_to="Candidates/Documents")),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("experience", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=200)),
                ("age", models.CharField(max_length=200)),
                (
                    "name_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HirePilot.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="Candidates/Documents"
                    ),
                ),
                ("candidate_extracted_data", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Interview", "Interview"),
                            ("Approved", "Approved"),
                            ("Decline", "Declined"),
                        ],
                        default="Pending",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "apply_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="apply date"
                    ),
                ),
                (
                    "candidate_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HirePilot.job"
                    ),
                ),
            ],
        ),
    ]
