# Generated by Django 4.2 on 2023-05-15 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('fulltime_partime', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=10)),
                ('offline_remote', models.CharField(choices=[('Offline', 'Offline'), ('Remote', 'Remote')], default='Offline', max_length=7)),
                ('submission_deadline', models.DateField(max_length=30)),
                ('selection_step', models.PositiveIntegerField()),
                ('salary_range', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
    ]
