# Generated by Django 4.1.3 on 2023-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry_type',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Engineering', 'Engineering'), ('Health Care', 'Health Care'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Aerospace', 'Aerospace'), ('Transport and Logistics', 'Transport and Logistics'), ('Banking and Finance', 'Banking and Finance'), ('Media and Entertainment', 'Media and Entertainment'), ('Professional Services', 'Professional Services'), ('Technology', 'Technology'), ('Others', 'Others')], default='Others', max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
