# Generated by Django 4.2 on 2023-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0002_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='Candidates/Documents')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
