# Generated by Django 4.1.3 on 2023-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0002_job_degree_job_language_alter_employer_industry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='selection_step',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two')], default='One', max_length=15),
        ),
    ]
