# Generated by Django 4.2 on 2023-07-10 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HirePilot", "0003_alter_job_selection_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="date_created",
            field=models.DateField(
                default=datetime.date.today, verbose_name="date created"
            ),
        ),
    ]
