# Generated by Django 4.2 on 2023-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0004_candidate_employer_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=55),
        ),
    ]
