# Generated by Django 4.2 on 2023-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HirePilot", "0004_alter_job_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Interview", "Interview"),
                    ("Approved", "Approved"),
                    ("Decline", "Declined"),
                ],
                default="Pending",
                max_length=9,
            ),
        ),
    ]
