# Generated by Django 4.2 on 2023-05-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0006_jobs_latest_date_jobs_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='latest_date',
        ),
    ]
