# Generated by Django 4.2 on 2023-05-29 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HirePilot', '0007_remove_jobs_latest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Candidates/Documents')),
                ('apply_date', models.DateField(default=django.utils.timezone.now, verbose_name='apply date')),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HirePilot.candidate')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HirePilot.jobs')),
            ],
        ),
    ]
